version: '3.8'
services:
  Crud-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: CRUD
  Redis:
    image: redis
    ports:
      - 6379:6379
